name: Deploy Portfolio

on:
  push:
    branches:
      - main  # The branch you push your source code to

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The target repository
          repository-name: rakeshkanna-rk/rakeshkanna-rk.github.io
          # The target branch
          branch: new-portfolio
          # The folder to deploy
          folder: dist
          # Requires a Personal Access Token (PAT) stored in GitHub Secrets
          token: ${{ secrets.DEPLOY_TOKEN }}
          # Ensures the branch is created if it doesn't exist
          single-commit: true
